### ISSUE TITLE
Data sources maxing out at 2500 rows

### ISSUE THREAD

**Issue by JesseCastro** [googledatastudio/experimental-visualizations#21]
When I'm testing my visualizations in Data Studio and I connect to either a BigQuery or Google Analytics data source, my request seems to max out at 2500 rows, even though my query is such that there should be more than that.  Is there a limit of 2500 rows, or have I misconfigured my request and/or data source?

**Comment by y3l2n** [comment]
The default is 2500 rows, but you can configure it (I need to add it to the documentation). 

For future reference: Questions about building community visualizations should be posted on StackOverflow or the developer forum, since issues here are specifically for issues related to the code in this repo. You can find those links on our [support page](https://developers.google.com/datastudio/support/)
